restylers:      
  - clang:  
        image: restyled/restyler-clang-format:v9.0.0
        command:
        - clang-format
        - "-i"
        arguments: []
        include:
        - "**/*.js"
        interpreters: []