language: node_js
node_js:
    - "stable"
branches:
  only:
  - master
install:
- npm i
jobs:
  include:
    - stage: test
      script: "npm run test"
    - stage: deploy
deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_KEY
    region: "us-west-2"
    app: "bluesEnElBalcon"
    env: "Bluesenelbalcon-env"
    bucket_name: $BUCKET_NAME
