os:
  - linux
dist: bionic
language: node_js
node_js:
    - "stable"
branches:
  only:
  - master
script:	
  - npm run build
  - zip -r $FILE_NAME server.js package.json
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-2"	    
  app: "bluesEnElBalcon"	   
  env: "Bluesenelbalcon-env"
  bucket: $bucket
  file: $FILE_NAME
